#!/bin/sh

# Path to molecules.git dir
ARGENT_MOLECULE_HOME="${ARGENT_MOLECULE_HOME:-/argent}"
export ARGENT_MOLECULE_HOME

# rootfs and bootfs tarball is generated by beaglebone image
export FIRST_PARTITION_START_CYL=1 # ~8Mb
export SD_FUSE="${ARGENT_MOLECULE_HOME}/boot/arm/odroid-u2-x2/sd_fuse/sd_fusing.sh"
export BOOT_PART_TYPE_INSIDE_ROOT="1"
exec "${ARGENT_MOLECULE_HOME}"/scripts/mkloopcard.sh "${ARGENT_MOLECULE_HOME}"/scripts/mkloopcard_odroid_u2_x2_chroot_hook.sh "${@}"
